---
name: sdnify
services:
  api:
    build:
      context: .
      dockerfile: ./dependencies/docker/api.Dockerfile
    ports:
      - 5000:5000
  mininet:
    build:
      context: .
      dockerfile: ./dependencies/docker/mininet.Dockerfile
    tty: true
    privileged: true
    environment:
     - DISPLAY
    volumes:
     - ./dependencies/docker/mininet.bashrc:/root/.bashrc
     - ./dependencies/docker/mininet.Xresources:/root/.Xresources
     - ./:/root/app/
     - /tmp/.X11-unix:/tmp/.X11-unix
     - /lib/modules:/lib/modules
  faucet:
    restart: always
    image: faucet/faucet:1.10.11
    environment:
     - FAUCET_CONFIG=/etc/faucet/faucet.yaml
     - FAUCET_CONFIG_STAT_RELOAD=1
    volumes:
      - ./dependencies/etc/faucet/:/etc/faucet/
      - ./dependencies/var/log/faucet/:/var/log/faucet/
    ports:
      - 6653:6653
      - 9302:9302
  gauge:
    image: faucet/gauge:1.10.11
    restart: always
    volumes:
      - ./dependencies/etc/faucet/:/etc/faucet/
      - ./dependencies/var/log/faucet/:/var/log/faucet/
    ports:
      - 6654:6653
      - 9303:9303
  prometheus:
    image: prom/prometheus:v2.55.0
    restart: always
    privileged: true
    volumes:
      - ./dependencies/etc/faucet/:/etc/faucet/
      - ./dependencies/var/log/faucet/:/var/log/faucet/
      - ./dependencies/etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./dependencies/etc/prometheus/faucet.rules.yml:/etc/prometheus/faucet.rules.yml
    ports:
      - 9090:9090
    links:
      - faucet
      - gauge
  grafana:
    image: grafana/grafana:11.2.2
    restart: always
    privileged: true
    ports:
      - 3000:3000
    links:
      - prometheus
